### ISSUE TITLE
[DWC2] No option to select the machine to connect to on mobile

### ISSUE THREAD

**Issue by Patrik-svobodik** [chrishamm/DuetWebControl#96] opened 2018-12-22 13:11 UTC
Hi, when I try to connect to my npm dev server from my iPhone it works "fine" (the bug from the other thread is still present) but for some reason when I click connect it doesn't let me choose the ip to connect to, it then just loops forever trying to connect

**Comment by chrishamm** [comment] 2018-12-22 13:14
Not a bug. DWC tries to connect to the remote ip if it does not run on
localhost so I won't address this. Multi machine support will be eventually
added but that will happen later when I have more time.

So what browser are you using on your computer?

On Saturday, December 22, 2018, Patrik-svobodik <notifications@github.com>
wrote:
> Hi, when I try to connect to my npm dev server from my iPhone it works
"fine" (the bug from the other thread is still present) but for some reason
when I click connect it doesn't let me choose the ip to connect to, it then
just loops forever trying to connect
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/pXB1pXPp284-GUsdEc_Ezqw0s4h12BVJuSntaIELerQNzEQ85J-2aqIRtFMBEydJP2lGFoamNAv7VWdb7XEELbfqg2E-myphFiW2VHp_KYQAW3AscWjNS6ygqSzZJTc0FcQKH970f1oKfI0BH5UAF0LKGQ=s0-d-e1-ft#https://github.com/notifications/beacon/AFpS2eWRW7rTHNanw1XkBtE8FY8y0M_0ks5u7i9xgaJpZM4ZfdyQ.gif>

**Comment by Patrik-svobodik** [comment] 2018-12-22 13:15
I use safari on both

**Comment by chrishamm** [comment] 2018-12-22 17:11
OK, thanks, I could confirm there was a bug in the reconnect logic which should be fixed now.
Eventually I will remove the connect button like I did in DWC1 but for now it can be handy for testing.

**Closed by chrishamm** 2018-12-22 17:11 UTC
