### ISSUE TITLE
Long pressing issue - mobile

### ISSUE THREAD

**Issue by jaysuk** [chrishamm/DuetWebControl#203] opened 2020-01-15 19:47 UTC
Long pressing on a gcode file whilst in mobile view cause the page to jump to the top.
The usual menu found in the online version does not appear.

**Comment by chrishamm** [comment] 2020-01-15 20:18
Works for me:

![Screenshot_20200115-211325_Firefox](https://user-images.githubusercontent.com/5919449/72468022-844a0e00-37dc-11ea-82a9-5ecb2423145c.png)

Can you provide more details? What browser are you using?

**Comment by jaysuk** [comment] 2020-01-15 21:04
It works correctly on my machine running RRF 3 stable, DWC 2.0.6 on a duet 2 ethernet.

It doesn't work on my other machine running RRF 3 stable, DWC 2.0.6 on a duet 3 V1 with raspberry pi attached.

**Comment by chrishamm** [comment] 2020-01-15 21:16
No issues on my Duet 3 + RPi either:

![Screenshot_20200115-221349_Firefox](https://user-images.githubusercontent.com/5919449/72472291-9465eb80-37e4-11ea-957e-6f638b197343.png)

I'll try to reproduce it with Chrome tomorrow.

**Comment by chrishamm** [comment] 2020-01-16 09:53
I could reproduce it in Chrome on Android so I'll check how I can fix this. Interestingly enough, the menu still pops up after the page jumps to the top.

**Comment by jaysuk** [comment] 2020-01-16 10:10
That was quick, I was just replying.

**Comment by chrishamm** [comment] 2020-01-24 12:18
Fixed in v2.0.7.

**Closed by chrishamm** 2020-01-24 12:18 UTC
