### ISSUE TITLE
Files are empty after downloading

### ISSUE THREAD

**Issue by anraf1001** [chrishamm/DuetWebControl#100] opened 2018-12-29 13:36 UTC
When I want to download a file from my Duet eg. "config.g". The downloaded one has only "null" inside it. The same happens when downloading several files in zip. I use DWC 2.0.0-RC2

**Comment by chrishamm** [comment] 2018-12-29 14:55
I cannot reproduce this. What browser are you using?

**Comment by anraf1001** [comment] 2018-12-29 15:17
Chrome

**Comment by chrishamm** [comment] 2019-01-02 16:18
Fixed in RC3.

**Closed by chrishamm** 2019-01-02 16:18 UTC
