### ISSUE TITLE
Job upload not working on iOS devices

### ISSUE THREAD

**Issue by TheBum** [chrishamm/DuetWebControl#180] opened 2019-11-23 17:29 UTC
When I attempt to upload a G-code file to my Duet 2 Maestro on my iPhone, the local files are shown but none of them are selectable for upload. This has happened most recently on DWC 2.04, but has been an issue in previous versions too.

**Comment by chrishamm** [comment] 2020-01-09 12:14
Well, it works under Mac OS X and since I don't have any other Apple devices, I'm not sure how I can address this. It's possible that Safari on iOS does not respect file input filters like other browsers.

**Comment by chrishamm** [comment] 2020-01-14 11:34
I was able to reproduce it and it should be fixed in the upcoming v2.0.6.

**Comment by TheBum** [comment] 2020-01-14 17:33
Good deal. Thanks!

**Comment by chrishamm** [comment] 2020-01-16 09:49
Fixed in DWC 2.0.6.

**Closed by chrishamm** 2020-01-16 09:49 UTC
